<?php
/**
 * This file has been automatically generated by Pomm's generator.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */

namespace AppBundle\Entity\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * Config
 *
 * Structure class for relation public.config.
 *
 * Class and fields comments are inspected from table and fields comments.
 * Just add comments in your database and they will appear here.
 * @see http://www.postgresql.org/docs/9.0/static/sql-comment.html
 *
 *
 *
 * @see RowStructure
 */
class Config extends RowStructure
{
    /**
     * __construct
     *
     * Structure definition.
     *
     * @access public
     */
    public function __construct()
    {
        $this
            ->setRelation('public.config')
            ->setPrimaryKey(['name'])
            ->addField('name', 'varchar')
            ->addField('value', 'varchar')
            ->addField('status', 'int')
            ;
    }
}
